#!/bin/bash
# 服务器部署命令清单
# 请在服务器上按顺序执行这些命令

echo "=========================================="
echo "步骤 1/6: 验证所有镜像已加载"
echo "=========================================="
echo "执行命令："
echo "docker images"
echo ""
echo "应该看到以下镜像："
echo "- python:3.11-slim"
echo "- postgres:15"
echo "- redis:7"
echo "- nginx:alpine"
echo "- uma-audit5-backend:latest"
echo ""
read -p "按回车继续..."

echo ""
echo "=========================================="
echo "步骤 2/6: 配置环境变量"
echo "=========================================="
echo "执行命令："
echo "cd /opt/uma-audit5"
echo "cp .env.example .env"
echo "vim .env"
echo ""
echo "需要修改以下配置："
echo "1. POSTGRES_PASSWORD=设置强密码"
echo "2. REDIS_PASSWORD=设置强密码"
echo "3. SECRET_KEY=生成随机密钥（下面会生成）"
echo "4. API_BASE_URL=http://8.136.59.48:8000"
echo ""
echo "生成 SECRET_KEY："
echo "openssl rand -hex 32"
echo ""
read -p "按回车继续..."

echo ""
echo "=========================================="
echo "步骤 3/6: 启动服务"
echo "=========================================="
echo "执行命令："
echo "cd /opt/uma-audit5"
echo "docker-compose up -d"
echo ""
read -p "按回车继续..."

echo ""
echo "=========================================="
echo "步骤 4/6: 查看服务状态"
echo "=========================================="
echo "执行命令："
echo "docker-compose ps"
echo ""
echo "应该看到所有服务状态为 Up"
echo ""
read -p "按回车继续..."

echo ""
echo "=========================================="
echo "步骤 5/6: 查看服务日志"
echo "=========================================="
echo "执行命令："
echo "docker-compose logs -f backend"
echo ""
echo "（按 Ctrl+C 退出日志查看）"
echo ""
read -p "按回车继续..."

echo ""
echo "=========================================="
echo "步骤 6/6: 验证 API 服务"
echo "=========================================="
echo "执行命令："
echo "curl http://localhost:8000/api/v1/health"
echo ""
echo "应返回："
echo '{"status":"healthy","timestamp":"..."}'
echo ""
echo "=========================================="
echo "部署完成！"
echo "=========================================="
echo ""
echo "访问地址："
echo "- API文档: http://8.136.59.48:8000/docs"
echo "- API健康检查: http://8.136.59.48:8000/api/v1/health"
echo ""
echo "常用命令："
echo "- 查看日志: docker-compose logs -f"
echo "- 重启服务: docker-compose restart"
echo "- 停止服务: docker-compose down"
echo "=========================================="
