"""Add project_type and additional fields to projects table

Revision ID: 199a61a88a9d
Revises: 
Create Date: 2025-09-09 12:18:26.489500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199a61a88a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.Enum('BUILDING', 'DECORATION', 'MUNICIPAL', 'LANDSCAPE', 'HIGHWAY', 'OTHER', name='projecttype'), nullable=True, comment='项目类型', default='OTHER'))
    op.add_column('projects', sa.Column('budget_amount', sa.Float(), nullable=True, comment='工程造价(万元)'))
    op.add_column('projects', sa.Column('price_base_date', sa.String(length=20), nullable=True, comment='价格基准日期'))
    op.add_column('projects', sa.Column('analysis_precision', sa.String(length=20), nullable=True, comment='分析精度', default='standard'))
    op.alter_column('projects', 'project_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_comment='项目UUID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'project_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_comment='项目UUID',
               existing_nullable=True)
    op.drop_column('projects', 'analysis_precision')
    op.drop_column('projects', 'price_base_date')
    op.drop_column('projects', 'budget_amount')
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###