"""add excel_region field to base_materials

Revision ID: 1e7e189f80bd
Revises: 4ac9bd62b2bf
Create Date: 2025-09-23 11:01:29.044506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7e189f80bd'
down_revision = '4ac9bd62b2bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_materials', sa.Column('excel_region', sa.String(length=100), nullable=True, comment='Excel原始地区信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_materials', 'excel_region')
    # ### end Alembic commands ###