"""add_category_id_to_base_materials

Revision ID: 2d7ecf790c2c
Revises: material_category_hierarchy
Create Date: 2025-09-09 12:08:55.700070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7ecf790c2c'
down_revision = 'material_category_hierarchy'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_materials', sa.Column('category_id', sa.Integer(), nullable=True, comment='所属分类ID'))
    op.create_foreign_key(op.f('fk_base_materials_category_id_material_categories'), 'base_materials', 'material_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_base_materials_category_id_material_categories'), 'base_materials', type_='foreignkey')
    op.drop_column('base_materials', 'category_id')
    # ### end Alembic commands ###