"""Remove unique constraint from material_code

Revision ID: 4ac9bd62b2bf
Revises: 465b2c4aeedf
Create Date: 2025-09-11 23:57:05.658194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac9bd62b2bf'
down_revision = '465b2c4aeedf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_base_materials_material_code', table_name='base_materials')
    op.create_index(op.f('ix_base_materials_material_code'), 'base_materials', ['material_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_base_materials_material_code'), table_name='base_materials')
    op.create_index('ix_base_materials_material_code', 'base_materials', ['material_code'], unique=False)
    # ### end Alembic commands ###